language: c++
sudo: required
dist: trusty

os:
  - linux
  
compiler:
  - gcc
  - clang
  
before_script:

  # Linux dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends debhelper cdbs qt5-qmake libqt5core5a libqt5widgets5 libqt5network5 libqt5gui5 libqt5printsupport5 libqt5svg5-dev qttools5-dev-tools qttools5-dev qt5-default libzip-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/"; fi

  - mkdir build
  - cd build

script:
  - cmake $CMAKE_ARGS ../.
  - make -j8
      
notifications:
  email:
    - diemmarkus@gmail.com
